### ISSUE TITLE
Allow built in Commands to be disabled by the user

### ISSUE THREAD

**Issue by ntindle** [Significant-Gravitas/Auto-GPT#3653]
All users must include the list of built-in commands in their prompts. This causes poor user experience, such as that listed in #3428. 

We should support disabling command categories by the user. 

Proposed Solution: add another config that disables loading a command if the configuration is in the list of disabled commands

Tasks:
- [ ] #3663 Move all command registrations into `main.py`
- [ ] #3667 Add an `env.template` entry for `DISABLED_COMMAND_CATEGORIES` and use it in `main.py`
- [ ] #3669 Document the available categories

**Comment by Emasoft** [comment]
Commands should be removed and converted in plugins.

**Comment by ntindle** [comment]
@Emasoft see #3652
